### ISSUE TITLE
composition operator not work on macOS MPB with Apple m1

### ISSUE THREAD

**Issue by mhfan** [blend2d/blend2d#181] opened 2023-10-30 03:47 UTC
Default output of bl_sample_capi is:

<img width="820" alt="image" src="https://github.com/blend2d/blend2d/assets/1171428/38e722f2-da9a-4fd2-bb42-f04372dea3f2">

After comment out [blContextSetCompOp(&ctx, BL_COMP_OP_DIFFERENCE);](https://github.com/blend2d/blend2d/blob/f25c7a22301f53c8d7303366fc398e3812ef4cb5/test/bl_sample_capi.c#L54) the output is:

<img width="820" alt="image" src="https://github.com/blend2d/blend2d/assets/1171428/635b3063-9a77-4068-bbb4-5eb9f7dc24c4">

And it seems a long stand bug, even revert the code back to commit [3d44046](https://github.com/blend2d/blend2d/commit/3d4404610642de1cdf732958c8dea6518a27ab46), following is the cmake output:

```
$ cmake .. -DBLEND2D_TEST=TRUE
-- The C compiler identification is AppleClang 15.0.0.15000040
-- The CXX compiler identification is AppleClang 15.0.0.15000040
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test __CxxFlag__fno_enforce_eh_specs
-- Performing Test __CxxFlag__fno_enforce_eh_specs - Failed
-- Performing Test __CxxFlag__mllvm___disable_loop_idiom_all
-- Performing Test __CxxFlag__mllvm___disable_loop_idiom_all - Success
-- Performing Test __CxxFlag__fno_threadsafe_statics
-- Performing Test __CxxFlag__fno_threadsafe_statics - Success
-- Performing Test __CxxFlag__fno_semantic_interposition
-- Performing Test __CxxFlag__fno_semantic_interposition - Failed
-- Performing Test __CxxFlag__fmerge_all_constants
-- Performing Test __CxxFlag__fmerge_all_constants - Success
-- Performing Test __CxxFlag__ftree_vectorize 
-- Performing Test __CxxFlag__ftree_vectorize - Success
-- Enabling build without linking to the C++ standard library
-- Performing Test __CxxFlag__mavx
-- Performing Test __CxxFlag__mavx - Failed   
-- Performing Test __CxxFlag__mavx2
-- Performing Test __CxxFlag__mavx2 - Failed  
-- Performing Test __CxxFlag__mavx512bw__mavx512dq__mavx512cd__mavx512vl
-- Performing Test __CxxFlag__mavx512bw__mavx512dq__mavx512cd__mavx512vl - Failed
** AsmJit Summary **
   ASMJIT_DIR=/Users/mhfan/Devel/blend2d/3rdparty/asmjit
   ASMJIT_TEST=FALSE
   ASMJIT_TARGET_TYPE=EMBED
   ASMJIT_DEPS=pthread
   ASMJIT_LIBS=pthread
   ASMJIT_CFLAGS=-DASMJIT_STATIC;-DASMJIT_NO_FOREIGN
   ASMJIT_PRIVATE_CFLAGS=-Wall;-Wextra;-Wconversion;-fno-math-errno;-fno-threadsafe-statics;-DASMJIT_STATIC;-DASMJIT_NO_FOREIGN
   ASMJIT_PRIVATE_CFLAGS_DBG=
   ASMJIT_PRIVATE_CFLAGS_REL=-O2;-fmerge-all-constants
** Blend2D Summary **
   BLEND2D_DIR=/Users/mhfan/Devel/blend2d
   BLEND2D_TEST=TRUE
   BLEND2D_TARGET_TYPE=SHARED
   BLEND2D_DEPS=c;m;pthread
   BLEND2D_LIBS=blend2d;c;m;pthread
   BLEND2D_CFLAGS=
   BLEND2D_PRIVATE_CFLAGS=-Wall;-Wextra;-fno-exceptions;-fno-rtti;-fno-math-errno;-fno-trapping-math;-fno-finite-math-only;-mllvm;--disable-loop-idiom-all;-fno-threadsafe-statics;-DASMJIT_STATIC;-DASMJIT_NO_FOREIGN;-DASMJIT_NO_STDCXX
   BLEND2D_PRIVATE_CFLAGS_DBG=
   BLEND2D_PRIVATE_CFLAGS_REL=-O2;-fmerge-all-constants;-ftree-vectorize
-- Configuring done (1.5s)
-- Generating done (0.1s)
-- Build files have been written to: /Users/mhfan/Devel/blend2d/build
```

**Comment by HowToExpect** [comment] 2023-11-23 03:05
I'm also in this situation

**Comment by kobalicek** [comment] 2023-12-05 16:44
Closing as a duplicate of https://github.com/blend2d/blend2d/issues/182

**Closed by kobalicek** 2023-12-05 16:44 UTC
