### ISSUE TITLE
Systematic use of uint32_t instead of enum

### ISSUE THREAD

**Issue by schauveau** [blend2d/blend2d#41] opened 2019-06-12 16:05 UTC
The systematic use of uint32_t instead of the enum type is making the API very painful to use. I do not care much that the compiler cannot check that I am using the right enum but I am spending far more time than acceptable trying to figure out which enum type I should use for each function parameter.

I do not now why that was done like that but I assume that there must be a reason (backward compatibility? consistency with the C api? make bindings easier? ...)  

If keeping uint32_t is really important then I propose the following approach that should solve the problem for the C++ api by providing the required information to Doxygen without changing the ABI.

1. Declare the following template type

        #include <type_traits>
        template<typename T> using bl_enum = typename std::underlying_type<T>::type;
or if you know that all enums are uint32_t

        template<typename T> using bl_enum = uint32_t;

2. And replace each `uint32_t` by `bl_enum<XXX>`  where XXX is the required enum type.

**Comment by amfogor** [comment] 2021-01-15 16:44
The issue has been open for quite some time. And still no answers.

Please, explain the reasoning.

It is indeed a big pain to use the functions taking or returning enums.
Maybe after using it for some time you just remember. But for newcomers it's a HUGE pain to figure out the possible values. Basically, you have to look at the sources for that.

**Comment by kobalicek** [comment] 2021-01-15 17:18
Blend2D will get enums in public C and C++ APIs - I just have so many internal branches at the moment so I would like to get them merged before I start something that would make all of them conflicting.

There is no reasoning behind not using enums in function signatures - When C-API was designed I didn't know in which direction C++ API would go in the future, so I kept both C and C++ APIs without having enum types in function signatures. The feedback is great so I think it's time to do something about it. However, I'm only willing to change function signatures and structs - I need a full control over structs in this case.

**Comment by amfogor** [comment] 2021-01-15 18:24
What do you mean by "full control over structs" ?
What would be the problem in using enums in structs?

**Comment by amfogor** [comment] 2021-01-15 18:53
Though tbh I don't know what structs you're talking about. If it's implementation-related, then whatever, no one should care, as long as it works.

**Comment by amfogor** [comment] 2021-01-15 19:40
Oh, right. I forgot that in C you can't specify the underlying type.

**Comment by kobalicek** [comment] 2021-01-15 19:42
There some solutions, like having always one enum in a list something like `ENUM_MAX_VALUE = 0xFFFFFFFFu`, but it's also pretty ugly to expose that. Maybe having something like `typedef uint32_t BLCompOp` and then using that typedef in the API would also solve the problem of not knowing what the function accepts.

I think improvements could be made without sacrificing portability, although having enums checked by the compiler is something I would welcome myself.

**Comment by amfogor** [comment] 2021-01-15 20:42
Maybe something like
```
BL_API BLResult BL_CDECL blContextEnd_(BLContextCore* self) BL_NOEXCEPT_C;
inline BLResultCode BL_CDECL blContextEnd(BLContextCore* self) BL_NOEXCEPT_C{ return (BLResultCode)blContextEnd_(self); }
```

**Comment by amfogor** [comment] 2021-01-15 23:17
> although having enums checked by the compiler is something I would welcome

Though I personally don't care for how friendly the C API is.

And you still could use enums in structs.
Yes, it would be `uint32_t` for C and `enum : uint32_t` for C++.
And yes it might feel like UB territory, since enums and underlying types don't alias each other, but no, these are two different languages we're talking about, and all we care about here is binary compatibility.
So since `enum : uint32_t` and `uint32_t` are binary compatible I don't see any problem so far.

**Comment by schauveau** [comment] 2021-01-16 07:41
> The problem with enums is that their size is dependent on compiler and compiler flags
@kobalicek This is irrelevant. C compilers are not going to change the size of their enums. As long as all the values fit in a 32 bit, the enum will be 32 bit. That as been the rule on 32 bit and 64 bit architectures for more than 40 years and this is not going to change because that would break thousands of C libraries. Using enums should be fine as long as the blend2d developers keep there enum values within a reasonable range.

**Comment by kobalicek** [comment] 2021-12-21 19:24
Closed as enums are now used correctly in public API.

Enums will not be used in some structs where a lesser type than the enum is used. This cannot be fixed if we want to keep C API, which we want.

**Closed by kobalicek** 2021-12-21 19:24 UTC
Labels: enhancement
