### ISSUE TITLE
raspberry pi 4b

### ISSUE THREAD

**Issue by bizehao** [blend2d/blend2d#114] opened 2021-07-14 01:39 UTC
raspberry pi 4b 64bit os Compilation failed，Does it support the raspberry pi os？

**Comment by bizehao** [comment] 2021-07-14 01:39
it is arm64

**Comment by kobalicek** [comment] 2021-07-14 23:41
I will check it out. In general it should compile, but without JIT. I'm not sure now whether JIT has to be explicitly disabled or whether cmake is able to handle that.

**Comment by bizehao** [comment] 2021-07-17 02:47
ok， how is it？

**Comment by jhmaloney** [comment] 2021-12-29 00:46
Blend2D has amazing performance on MacOS and Linux.

However, I've also hit compiler errors on the Raspberry Pi (model 4B). One error was in matrix.cpp. This code:

void blTransformRtInit(BLRuntimeContext* rt) noexcept {
#if !defined(BL_TARGET_OPT_SSE2)
  blUnused(rt);
  BLMapPointDArrayFunc* funcs = blMatrix2DMapPointDArrayFuncs;

  blAssignFunc(&funcs[BL_MATRIX2D_TYPE_IDENTITY ], blMatrix2DMapPointDArrayIdentity);
  blAssignFunc(&funcs[BL_MATRIX2D_TYPE_TRANSLATE], blMatrix2DMapPointDArrayTranslate);
  blAssignFunc(&funcs[BL_MATRIX2D_TYPE_SCALE    ], blMatrix2DMapPointDArrayScale);
  blAssignFunc(&funcs[BL_MATRIX2D_TYPE_SWAP     ], blMatrix2DMapPointDArraySwap);
  blAssignFunc(&funcs[BL_MATRIX2D_TYPE_AFFINE   ], blMatrix2DMapPointDArrayAffine);
  blAssignFunc(&funcs[BL_MATRIX2D_TYPE_INVALID  ], blMatrix2DMapPointDArrayAffine);
#endif

is not in the BLTransformPrivate namespace, so the entry points need to be qualified like this:

  BLTransformPrivate::blMatrix2DMapPointDArrayIdentity

I'm surprised I didn't get the same error on MacOS and Linux, but it was easy to fix.

The error I'm stuck on is this:

$ cmake --build .
[  1%] Building CXX object CMakeFiles/blend2d.dir/src/blend2d/pixelops/interpolation.cpp.o
In file included from /home/pi/Desktop/blend2d/blend2d/src/blend2d/pixelops/../simd_neon_p.h:11,
                 from /home/pi/Desktop/blend2d/blend2d/src/blend2d/pixelops/../simd_p.h:19,
                 from /home/pi/Desktop/blend2d/blend2d/src/blend2d/pixelops/../math_p.h:11,
                 from /home/pi/Desktop/blend2d/blend2d/src/blend2d/pixelops/interpolation.cpp:8:
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h: In function ‘uint32_t SIMD::{anonymous}::v_get_u32(const Vec128I&)’:
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h:6286:1: error: inlining failed in call to always_inline ‘uint32_t vgetq_lane_u32(uint32x4_t, int)’: target specific option mismatch
 vgetq_lane_u32 (uint32x4_t __a, const int __b)
 ^~~~~~~~~~~~~~
In file included from /home/pi/Desktop/blend2d/blend2d/src/blend2d/pixelops/../simd_p.h:19,
                 from /home/pi/Desktop/blend2d/blend2d/src/blend2d/pixelops/../math_p.h:11,
                 from /home/pi/Desktop/blend2d/blend2d/src/blend2d/pixelops/interpolation.cpp:8:
/home/pi/Desktop/blend2d/blend2d/src/blend2d/pixelops/../simd_neon_p.h:188:80: note: called from here
 BL_INLINE uint32_t v_get_u32(const Vec128I& x) noexcept { return vgetq_lane_u32(x.u32, 0); }
                                                                  ~~~~~~~~~~~~~~^~~~~~~~~~
make[2]: *** [CMakeFiles/blend2d.dir/build.make:999: CMakeFiles/blend2d.dir/src/blend2d/pixelops/interpolation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/blend2d.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Any idea how to fix that?

Many thanks for creating Blend2D!

**Comment by jhmaloney** [comment] 2021-12-29 00:54
P.S. I get the error with either setting of the BLEND2D_NO_JIT flag.

**Comment by kobalicek** [comment] 2021-12-30 06:42
@jhmaloney Hi, can you try again with the recent master? I tried it on RPI4 with GCC/Clang and I was able to fix some issues, not sure it fixes all your issues though.

**Comment by jhmaloney** [comment] 2021-12-30 11:09
Thanks for the quick response! The issue with matrix.cpp is fixed.

However, I am still getting this error:
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h:6286:1: error: inlining failed in call to always_inline ‘uint32_t vgetq_lane_u32(uint32x4_t, int)’: target specific option mismatch
vgetq_lane_u32 (uint32x4_t __a, const int __b)

I am attempting to build this on my Raspberry Pi 4, which has gcc version "Raspbian 8.3.0-6+rpi1). That does not appear to be a clang-based gcc. Could that be the problem?

**Comment by kobalicek** [comment] 2021-12-30 11:24
I'm not sure what the issue is - I tried with GCC 10, which is in Ubuntu, and that worked without any problem.

Maybe it needs some target specific -m option, like `-mneon`?

**Comment by jhmaloney** [comment] 2021-12-30 12:18
gcc 8.3 seems pretty old so I'm guessing that's the issue. Raspberry Pi just released a new version of Raspian OS this month based on Debian Bullseye, and I'm guessing that includes an updated gcc.

However, many Pi users won't upgrade immediately and some of them may want to build Blend2D, and I'm happy to keep testing that scenario.

I'm not in a huge rush. If you think this can be fixed by adding a compiler flag, then I will wait for your fix and see if that allows Blend2D to build on a Raspberry Pi system that hasn't yet been upgraded to "Bullseye". 

FYI, I'm the lead developer of MicroBlocks, a free, open source, beginner-focused blocks programming language for the micro:bit and other educational microcontrollers. MicroBlocks runs on Windows, MacOS, Linux, and Raspberry Pi. It currently uses Cairo for rendering but I'm considering switching to Blend2D. Preliminary tests suggest that we'd get a 3x to 12x increase in rendering speed. That would make the the block programming system feel snappier, especially on slower computers. (Many schools have old hardware that was low-end to begin with.)

I've been able to build Blend2D for MacOS Mojave and multiple versions of Ubuntu  (32-bit and 64-bit). I'm working on Windows under MinGW (I need to update MinGW) and, as you know, Raspian.

**Comment by jhmaloney** [comment] 2021-12-30 12:22
BTW, will the JIT pipeline eventually work on Raspberry Pi? How much speedup would that provide for solid-color filled polygons and stroked paths?

**Comment by kobalicek** [comment] 2021-12-31 00:12
Well, I think this is an issue in Blend2D in the end - it should either set `-mneon` in `CMakeLists.txt` or it should check for neon in SIMD helpers. I will fix this.

Yeah, this will get working on AArch64 including JIT, I'm not sure I can finalize everything related to this in 2022 though, but I think I can get at least basics working. In addition, I'm preparing a two-stage pipeline, which will get all features that JIT has at the moment without requiring JIT, for making it possible to run Blend2D on any other architecture or where JIT is not possible.

**Comment by jhmaloney** [comment] 2022-01-17 13:48
Can I set -mneon by manually editing CMakeLists.txt to build and test Blend2d on the RaspberryPi? How would I do that? Thanks!

**Comment by kobalicek** [comment] 2022-01-17 14:05
Yeah, I think `CXXFLAGS="-mneon" cmake ...` should work without even editing CMakeLists - I'm not sure how to detect the target platform in cmake yet to be able to do that, maybe I can just detect the flag similarly to how `-msse2` is detected for x86.

**Comment by jhmaloney** [comment] 2022-01-18 02:06
No luck. I get the compiler error: "unrecognized command line option '-mneon'. I'm guessing the default Raspbian compiler, gcc 8.3.0, is simply not up to the job. I will try upgrading to Bullseye and, if that doesn't work, try installing a different compiler. Will keep you posted.

**Comment by jhmaloney** [comment] 2022-01-18 18:17
As I understand it, the Raspberry Pi has a 64-bit capable ARM processor, but the operating system is running in 32-bit mode. I'm guessing the compiler is set up to generate 32-bit instructions to be compatible with all their libraries. That ambiguity might be at the root of this problem.

FYI, this is not urgent. I'm super happy with Blend2D on MacOS, 32-bit and 64-bit Linux, and Windows (all Intel). On all those platforms, it is 3 to 10 times faster than Cairo for simple vector paths (filled and stroked), which is what I need it for, and I'm in the process of changing MicroBlocks to use it. When it works on Raspberry Pi, I'll use it there as well. For now, I can just continue to use Cairo.

Blend2D is a great project, super high quality, fast, and compact. I really appreciate all the hard work you've put into it.

**Comment by kobalicek** [comment] 2022-01-18 18:33
I see, btw I'm testing Blend2D on 64-bit RPI 4 (8GB RAM model), but I have installed Ubuntu on that machine (not raspbian).

I still think that this is an issue in Blend2D, GCC/tooling is probably right. I think I would need a 32-bit raspbian to be able to fix this, however, I think it would be some triviality.

BTW what about `-march=armv8-a+simd` - would that work?

**Comment by jhmaloney** [comment] 2022-01-20 20:05
SOLVED!

`-march=armv8-a+simd` didn't work but `-mfpu=neon` did, and with that flag blend2d compiles and runs on both Raspberry Pi OS Buster (the previous release) and Bullseye (the latest release). Yay! I tested the build process with clean installs of both version of Raspberry Pi OS. I just needed to add cmake with:

`sudo apt install cmake`

I then followed your instructions [here](https://blend2d.com/doc/build-instructions.html) with minor change to the first cmake command:

`CXXFLAGS="-mfpu=neon" cmake .. -DCMAKE_BUILD_TYPE=Release`

Performance on my very specific benchmark is about 2.5 times Cairo, which is quite respectable.

**Comment by kobalicek** [comment] 2023-08-08 14:40
@jhmaloney Would you be able to test the current release as well?

**Comment by jhmaloney** [comment] 2023-08-08 20:52
Do you mean the current Raspberry Pi OS release?

I can give it a try when I get some time (i.e. not immediately). It's been quite a while since I did anything on my Raspberry Pi so I'm guessing a bunch of stuff may no longer work. Feel free to ping me again in September if I haven't responded by then.

**Comment by kobalicek** [comment] 2023-08-08 21:01
@jhmaloney I meant the current Blend2D release. I've got it working on OrangePI, but I have no RPI to test it out.

And yeah, no rush :)

**Comment by kobalicek** [comment] 2023-09-01 18:15
I'm closing this issue, if there is a compilation problem with a latest release / master branch, please open a new issue and it will get fixed.

**Closed by kobalicek** 2023-09-01 18:15 UTC
