### ISSUE TITLE
vs2017 can not compile this lib...

### ISSUE THREAD

**Issue by sdragonx** [blend2d/blend2d#159] opened 2023-01-28 18:36 UTC
Some errors have occurred, probably due to duplicate function names.
Which c++version of this library is used? c++14？ c++17？

**Comment by kobalicek** [comment] 2023-01-28 18:58
Hello, I don't have VS2017, so I cannot help unless you provide more information about the issue (compile log, etc). Blend2D only needs C++11, so I guess VS2017 should theoretically compile it

**Comment by sdragonx** [comment] 2023-04-27 14:18
Many library authors nowadays do not care about the use of C++version features.
Vs2017 supports c++11.
I am not sending this to require you to make any necessary corrections, just to let you know.
For the use of C++features, the requirement is relatively high, which is to have a smaller usable environment.
This library looks good, but I am currently unable to consider it.

**Comment by kobalicek** [comment] 2023-04-27 17:04
Well, as I stated above - I'm fine with supporting VS2017, but somebody would have to maintain that support, which would mean to at least send PR now to correct the build, and afterwards when it gets broken again. The problem is, GH actions do not support VS2017 anymore, and I don't use it - this means that it's difficult to verify the build.

I don't think Blend2D has any specific requirements - it really just needs C++11 and it only uses a subset of C++ features (it doesn't even rely on a C++ standard library).

From my own experience - older MS compilers were extremely buggy and sometimes require workarounds - especially the whole constexpr feature was extremely broken in the past and some workarounds in Blend2D still exist. It's an endeavor I don't wanna experience again :)

**Comment by kobalicek** [comment] 2023-12-05 16:49
I'm closing this issue as I don't use VS2017 and the support for this compiler is not official (VS2019+ 
is official).

If you want to support VS2017 compiler, please reopen this issue and provide a pull request. I would be happy to review it.

BTW Blend2D only needs C++11.

**Closed by kobalicek** 2023-12-05 16:49 UTC
