### ISSUE TITLE
text glyph draw failed on some fonts which successd on After Effects

### ISSUE THREAD

**Issue by dongyado** [blend2d/blend2d#113] opened 2021-07-02 03:31 UTC
Hi, i've test blend2d to draw text with fonts with your own example :
https://github.com/blend2d/blend2d-samples/blob/master/getting-started/src/bl-getting-started-8.cpp

i've changed code like this, used a FZBiaoZJ.OTF which worked on AE with same chars:
only "text" "是" "魔"  can draw success . i'll attach the font file. thanks a lot.
[test_fonts.zip](https://github.com/blend2d/blend2d/files/6751896/test_fonts.zip)

```
#include <blend2d.h>
#include <stdio.h>
#include <string.h>

int main(int argc, char* argv[]) {
  BLImage img(480, 480, BL_FORMAT_PRGB32);
  BLContext ctx(img);

  ctx.setCompOp(BL_COMP_OP_SRC_COPY);
  ctx.fillAll();
  ctx.setFillStyle(BLRgba32(0xFFFFFFFF));

  BLFontFace face;
  BLResult err = face.createFromFile("/home/slayer/Desktop/workspace/fonts/FZBiaoZJ.OTF");
  if (err) {
    printf("Failed to load a font-face (err=%u)\n", err);
    return 1;
  }

  BLFont font;
  font.createFromFace(face, 20.0f);

  BLFontMetrics fm = font.metrics();
  BLTextMetrics tm;
  BLGlyphBuffer gb;

  BLPoint p(20, 190 + fm.ascent);
  const char* text = "text\n这\n是\n魔\n术\n贴\n的\n设\n计";
  for (;;) {
    const char* end = strchr(text, '\n');
    gb.setUtf8Text(text, end ? (size_t)(end - text) : SIZE_MAX);
    font.shape(gb);
    font.getTextMetrics(gb, tm);

    p.x = (480.0 - (tm.boundingBox.x1 - tm.boundingBox.x0)) / 2.0;
    ctx.fillGlyphRun(p, font, gb.glyphRun());
    p.y += fm.ascent + fm.descent + fm.lineGap;

    if (!end) break;
    text = end + 1;
  }
  ctx.end();
  img.writeToFile("bl-getting-started-8.bmp");

  return 0;
}
```

**Comment by kobalicek** [comment] 2021-07-14 23:42
I will have to find some time to investigate this, please be patient

**Comment by dongyado** [comment] 2021-07-20 05:51
thanks, i'll wait

**Comment by panjunqiu** [comment] 2021-11-09 08:40
I also found the same problem. Is there any progress?

**Comment by kobalicek** [comment] 2022-08-01 20:41
Can you retest this? I have fixed a small bug in OTF CFF decoding that prevented some glyphs from being decoded

**Comment by kobalicek** [comment] 2022-08-07 19:41
I have tried to render the text and I get the followin:

![image](https://user-images.githubusercontent.com/6491301/183308226-b95ea0a2-ae5f-48b4-a323-e0832e5d4970.png)

Is this okay now?

**Comment by kobalicek** [comment] 2023-06-18 09:40
Closing as I think this has been fixed, please reopen if the problem is still there

**Closed by kobalicek** 2023-06-18 09:40 UTC
