### ISSUE TITLE
Unused variable warnings

### ISSUE THREAD

**Issue by prideout** [blend2d/blend2d#42] opened 2019-06-18 14:54 UTC
I'm able to build blend2d from a fresh clone with very little pain (nice job!) but see lots of warnings:
```
[8/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/blgradient_sse2.cpp.o
../extern/blend2d/src/blend2d/blgradient_sse2.cpp:149:7: warning: unused label 'OnLoop_End' [-Wunused-label]
      BL_SIMD_LOOP_32x4_MAIN_END(Loop)
      ^
../extern/blend2d/src/blend2d/./blsimd_p.h:70:79: note: expanded from macro 'BL_SIMD_LOOP_32x4_MAIN_END'
                                                                              \
                                                                              ^
<scratch space>:8:1: note: expanded from here
OnLoop_End
^
1 warning generated.
[10/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/blfont.cpp.o
../extern/blend2d/src/blend2d/blfont.cpp:989:58: warning: unused parameter 'path' [-Wunused-parameter]
static BLResult BL_CDECL blFontDummyPathSink(BLPathCore* path, const void* info, void* closure) noexcept {
                                                         ^
../extern/blend2d/src/blend2d/blfont.cpp:989:76: warning: unused parameter 'info' [-Wunused-parameter]
static BLResult BL_CDECL blFontDummyPathSink(BLPathCore* path, const void* info, void* closure) noexcept {
                                                                           ^
../extern/blend2d/src/blend2d/blfont.cpp:989:88: warning: unused parameter 'closure' [-Wunused-parameter]
static BLResult BL_CDECL blFontDummyPathSink(BLPathCore* path, const void* info, void* closure) noexcept {
                                                                                       ^
3 warnings generated.
[14/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/blgradient.cpp.o
../extern/blend2d/src/blend2d/blgradient.cpp:926:14: warning: unused variable 'result' [-Wunused-variable]
    BLResult result = blGradientRemoveStop(self, index);
             ^
1 warning generated.
[21/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/blpipedefs.cpp.o
../extern/blend2d/src/blend2d/blpipedefs.cpp:506:10: warning: unused variable 'angle' [-Wunused-variable]
  double angle = values.angle;
         ^
../extern/blend2d/src/blend2d/blpipedefs.cpp:502:138: warning: unused parameter 'extendMode' [-Wunused-parameter]
static BL_INLINE uint32_t blPipeFetchDataInitConicalGradient(BLPipeFetchData* fetchData, const BLConicalGradientValues& values, uint32_t extendMode, const BLMatrix2D& m, const BLMatrix2D& mInv) noexcept {
                                                                                                                                         ^
2 warnings generated.
[29/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/blpixelconverter_avx2.cpp.o
../extern/blend2d/src/blend2d/blpixelconverter_avx2.cpp:238:23: warning: unused variable 'dstInfo' [-Wunused-variable]
  const BLFormatInfo& dstInfo = blPixelConverterFormatInfo[dstFormat];
                      ^
1 warning generated.
[36/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/blpath.cpp.o
../extern/blend2d/src/blend2d/blpath.cpp:1899:91: warning: unused parameter 'fitFlags' [-Wunused-parameter]
BLResult blPathFitTo(BLPathCore* self, const BLRange* range, const BLRect* rect, uint32_t fitFlags) noexcept {
                                                                                          ^
1 warning generated.
[40/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/blpixelconverter.cpp.o
../extern/blend2d/src/blend2d/blpixelconverter.cpp:818:12: warning: unused variable 'isGray' [-Wunused-variable]
      bool isGray = (srcInfo.flags & BL_FORMAT_FLAG_LUM) != 0;
           ^
../extern/blend2d/src/blend2d/blpixelconverter.cpp:943:12: warning: unused variable 'isGray' [-Wunused-variable]
      bool isGray = (dstInfo.flags & BL_FORMAT_FLAG_LUM) != 0;
           ^
2 warnings generated.
[51/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/codec/bljpegcodec.cpp.o
../extern/blend2d/src/blend2d/codec/bljpegcodec.cpp:1530:105: warning: unused parameter 'dst' [-Wunused-parameter]
static BLResult BL_CDECL blJpegCodecImplCreateEncoder(const BLImageCodecImpl* impl, BLImageEncoderCore* dst) noexcept {
                                                                                                        ^
../extern/blend2d/src/blend2d/codec/bljpegcodec.cpp:48:22: warning: unused variable 'blJpegExifLE' [-Wunused-const-variable]
static const uint8_t blJpegExifLE[4] = { 0x49, 0x49, 0x2A, 0x00 };
                     ^
../extern/blend2d/src/blend2d/codec/bljpegcodec.cpp:49:22: warning: unused variable 'blJpegExifBE' [-Wunused-const-variable]
static const uint8_t blJpegExifBE[4] = { 0x4D, 0x4D, 0x00, 0x2A };
                     ^
3 warnings generated.
[56/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/blpathstroke.cpp.o
../extern/blend2d/src/blend2d/blpathstroke.cpp:797:87: warning: unused parameter 'n1' [-Wunused-parameter]
  BL_INLINE BLResult dullRoundJoin(BLPathAppender& out, uint32_t side, const BLPoint& n1, const BLPoint& w1) noexcept {
                                                                                      ^
../extern/blend2d/src/blend2d/blpathstroke.cpp:31:25: warning: unused variable 'BL_STROKE_COLLINEARITY_EPSILON_SQ' [-Wunused-const-variable]
static constexpr double BL_STROKE_COLLINEARITY_EPSILON_SQ = blSquare(BL_STROKE_COLLINEARITY_EPSILON);
                        ^
2 warnings generated.
[61/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/codec/blpngcodec.cpp.o
../extern/blend2d/src/blend2d/codec/blpngcodec.cpp:1331:104: warning: unused parameter 'dst' [-Wunused-parameter]
static BLResult BL_CDECL blPngCodecImplCreateEncoder(const BLImageCodecImpl* impl, BLImageEncoderCore* dst) noexcept {
                                                                                                       ^
1 warning generated.
[63/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/opentype/blotcff.cpp.o
../extern/blend2d/src/blend2d/opentype/blotcff.cpp:484:27: warning: unused variable 'kCFFValueStackSizeV2' [-Wunused-const-variable]
static constexpr uint32_t kCFFValueStackSizeV2 = 513;
                          ^
1 warning generated.
[70/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/opentype/blotlayout.cpp.o
../extern/blend2d/src/blend2d/opentype/blotlayout.cpp:500:12: warning: unused variable 'attachListOffset' [-Wunused-variable]
  uint32_t attachListOffset         = gdef->v1_0()->attachListOffset();
           ^
../extern/blend2d/src/blend2d/opentype/blotlayout.cpp:501:12: warning: unused variable 'ligCaretListOffset' [-Wunused-variable]
  uint32_t ligCaretListOffset       = gdef->v1_0()->ligCaretListOffset();
           ^
../extern/blend2d/src/blend2d/opentype/blotlayout.cpp:503:12: warning: unused variable 'markGlyphSetsDefOffset' [-Wunused-variable]
  uint32_t markGlyphSetsDefOffset   = version >= 0x00010002u ? uint32_t(gdef->v1_2()->markGlyphSetsDefOffset()) : uint32_t(0);
           ^
../extern/blend2d/src/blend2d/opentype/blotlayout.cpp:504:12: warning: unused variable 'itemVarStoreOffset' [-Wunused-variable]
  uint32_t itemVarStoreOffset       = version >= 0x00010003u ? uint32_t(gdef->v1_3()->itemVarStoreOffset()    ) : uint32_t(0);
           ^
../extern/blend2d/src/blend2d/opentype/blotlayout.cpp:1870:12: warning: unused variable 'featureParamsOffset' [-Wunused-variable]
  uint32_t featureParamsOffset = table->featureParamsOffset();
           ^
../extern/blend2d/src/blend2d/opentype/blotlayout.cpp:1924:14: warning: unused variable 'lookupOrderOffset' [-Wunused-variable]
    uint32_t lookupOrderOffset = langSys->lookupOrderOffset();
             ^
../extern/blend2d/src/blend2d/opentype/blotlayout.cpp:1902:12: warning: unused variable 'langSysDefault' [-Wunused-variable]
  uint32_t langSysDefault = table->langSysDefault();
           ^
7 warnings generated.
[75/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/pipegen/blcompoppart.cpp.o
../extern/blend2d/src/blend2d/pipegen/blcompoppart.cpp:1329:10: warning: unused variable 'useSa' [-Wunused-variable]
    bool useSa = hasSa() || hasMask;
         ^
1 warning generated.
[83/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/src/blend2d/pipegen/blpipegenruntime.cpp.o
../extern/blend2d/src/blend2d/pipegen/blpipegenruntime.cpp:179:114: warning: unused parameter 'cache' [-Wunused-parameter]
static BLPipeFillFunc BL_CDECL blPipeGenRuntimeTest(BLPipeRuntime* self_, uint32_t signature, BLPipeLookupCache* cache) noexcept {
                                                                                                                 ^
1 warning generated.
[107/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/__/asmjit/src/asmjit/core/ralocal.cpp.o
../extern/asmjit/src/asmjit/core/ralocal.cpp:833:79: warning: unused parameter 'cont' [-Wunused-parameter]
Error RALocalAllocator::allocBranch(InstNode* node, RABlock* target, RABlock* cont) noexcept {
                                                                              ^
1 warning generated.
[118/124] Building CXX object extern/blend2d/CMakeFiles/blend2d.dir/__/asmjit/src/asmjit/x86/x86internal.cpp.o
../extern/asmjit/src/asmjit/x86/x86internal.cpp:1318:13: warning: unused function 'dumpAssignment' [-Wunused-function]
static void dumpAssignment(String& sb, const X86FuncArgsContext& ctx) noexcept {
```

**Comment by kobalicek** [comment] 2019-06-18 17:05
Yeah, these warnings annoy me too, however, some of them are caused by unfinished code and I prefer to see the warnings instead of silencing them. Others warnings and warnings that come from asmjit should be fixed though and I will work on that.

**Comment by kobalicek** [comment] 2022-12-17 19:57
Closing as there is only one remaining warning that pops in Blend2D builds and that one will be fixed once the feature is implemented. Thanks for the report!

**Closed by kobalicek** 2022-12-17 19:57 UTC
Labels: todo
